INSERT INTO AUTHORITY (USER, ROLE) VALUES ('Shrikant', 'ADMIN');
INSERT INTO AUTHORITY (USER, ROLE) VALUES ('admin', 'ADMIN');
INSERT INTO AUTHORITY (USER, ROLE) VALUES ('Virendra', 'USER');
INSERT INTO AUTHORITY (USER, ROLE) VALUES ('user', 'USER');