INSERT INTO GROCERY (NAME, PRICE, INVENTORY) VALUES ('Amul Butter', 100, 10);
INSERT INTO GROCERY (NAME, PRICE, INVENTORY) VALUES ('Fortune Oil', 500, 10);
INSERT INTO GROCERY (NAME, PRICE, INVENTORY) VALUES ('Parle-G', 10, 10);
INSERT INTO GROCERY (NAME, PRICE, INVENTORY) VALUES ('Apple(1 kg)', 180, 10);